name: Build and upload notebook to TIRA
on: 
  push:
  workflow_dispatch:
    inputs:
      notebook:
        description: The path to the Jupyter notebook that you want to submit to TIRA.
        required: true
        type: string
        default: retrieval-baseline.ipynb
      dataset:
        type: choice
        description: The dataset to use when submitting the notebook.
        options: 
        - ir-lab-wise-2024/subsampled-ms-marco-deep-learning-20241201-training
        - ir-lab-wise-2024/subsampled-ms-marco-rag-20241202-training
        - ir-lab-wise-2024/ms-marco-rag-20241203-test
        default: ir-lab-wise-2024/subsampled-ms-marco-deep-learning-20241201-training
jobs:
  docker-build:
    name: Build and upload notebook to TIRA
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check TIRA login
        run: |
          if [[ "${{ secrets.TIRA_CLIENT_TOKEN }}" == "" ]]; then
            echo "You must configure the TIRA_CLIENT_TOKEN secret."
            exit 1
          fi
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up QEMU for Docker build
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx tools
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for notebook
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: information-retrieval-exercise
          cache-from: type=local,src=.cache
          cache-to: type=local,dest=.cache
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install tira
      - name: Test and upload Docker image
        run: |
          tira-run \
          --tira-client-token ${{ secrets.TIRA_CLIENT_TOKEN }} \
          --input-dataset ${{ inputs.dataset || 'ir-lab-wise-2024/subsampled-ms-marco-deep-learning-20241201-training' }} \
          --image information-retrieval-exercise \
          --command "jupyter-execute /app/${{ inputs.notebook || 'retrieval-baseline.ipynb' }}" \
          --fail-if-output-is-empty \
          --push ${{ github.event== 'worflow_dispatch' }} \
          --output-directory .tira/output/
